# Generated by Django 5.1.4 on 2025-05-06 06:51

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uniform_image_uniform_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='images/uniforms/'),
        ),
    ]
