# Generated by Django 5.1.4 on 2025-05-06 08:44

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_uniform_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniform',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='images/uniforms/'),
        ),
    ]
