# Generated by Django 5.1.4 on 2025-05-06 06:51

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_checkin_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='images/company/logo/'),
        ),
    ]
