# Generated by Django 5.1.4 on 2025-05-06 08:44

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_alter_companyprofile_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='images/company/logo/'),
        ),
    ]
