# Generated by Django 5.1.4 on 2025-05-11 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_companyprofile_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMystaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('job_role', models.CharField(max_length=200)),
                ('employee_type', models.CharField(max_length=200)),
                ('invitation_code', models.CharField(max_length=8, null=True)),
                ('code_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_joined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
            ],
            options={
                'verbose_name_plural': 'Invite Staff',
                'ordering': ['-created_at'],
                'unique_together': {('staff_email', 'client')},
            },
        ),
    ]
