# Generated by Django 5.1.4 on 2025-05-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_invitemystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemystaff',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
