# Generated by Django 5.1.4 on 2025-06-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_invitemystaff_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='checkin_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('late', 'LATE')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkout_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED'), ('late', 'LATE')], default='pending', max_length=10),
        ),
    ]
