# Generated by Django 5.1.4 on 2025-05-06 06:51

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='staff/cv/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='video_cv',
            field=models.FileField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='staff/video_resume/'),
        ),
    ]
