# Generated by Django 5.1.4 on 2025-05-06 08:44

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_cv_alter_staff_video_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='avatar',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='staff/avatar/'),
        ),
    ]
