# Generated by Django 5.1.4 on 2025-06-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
