# Generated by Django 5.1.4 on 2025-06-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_chatmessae_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='perticipants',
            new_name='participants',
        ),
    ]
