# Generated by Django 5.1.4 on 2025-05-06 06:51

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_faq_termsandconditions_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='termsandconditions',
            name='document',
            field=models.FileField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='terms_and_conditions/'),
        ),
    ]
