# Generated by Django 5.1.4 on 2025-05-07 09:01

import project.s3bucket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_report_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetmeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, storage=project.s3bucket.CustomS3Storage(), upload_to='letme_review/')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Letme Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
