# Generated by Django 5.1.4 on 2025-05-08 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_companyprofile_company_logo'),
        ('dashboard', '0006_letmereview_is_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyListed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_show', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.companyprofile')),
            ],
            options={
                'verbose_name_plural': 'Company Listed',
                'ordering': ['-created_at'],
            },
        ),
    ]
