# Generated by Django 5.1.4 on 2025-05-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_companylisted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylisted',
            options={'ordering': ['order'], 'verbose_name_plural': 'Company Listed'},
        ),
    ]
